version: '4.1.1'
services:
   web:
       build: ./
       command: python manage.py runserver 0.0.0.0:8000
       ports:
           - 8000:8000
       environment:
         - DB_HOST=db
         - DB_NAME=DBPassword_Manager
         - DB_USER=UserPasswordManager
         - DB_PASSWORD=Qwerty

       depends_on:
           - db
   db:
     image: postgres:13
     expose:
       - "5432"
     ports:
       - '5432:5432'
     environment:
        - POSTGRES_USER=UserPasswordManager
        - POSTGRES_PASSWORD=Qwerty
        - POSTGRES_DB=DBPassword_Manager
     restart: always
     command: -p 5432







